{% set version = "1.2" %}
{% set name = "gf2x" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gforge.inria.fr/frs/download.php/file/36934/{{ name }}-{{ version }}.tar.gz
  sha256: 61427ffa03b5006aa154def6dce8bcff0fdefb3bd72f43fb1a7b4fdd6b80db34
  patches:
    # patches from https://github.com/sagemath/sage
    - patches/0001-generic_really_is_generic.patch


build:
  number: 2
  skip: true        # [win]
  track_features:
    - gf2x
  run_exports:
    - {{ pin_subpackage('gf2x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool
    - automake

test:
  commands:
    - test -f $PREFIX/include/gf2x.h
    - test -f $PREFIX/lib/lib{{ name }}.a
    - test -f $PREFIX/lib/lib{{ name }}.so         # [linux]
    - test -f $PREFIX/lib/lib{{ name }}.dylib      # [osx]

about:
  home: http://gf2x.gforge.inria.fr
  dev_url: http://gforge.inria.fr/projects/gf2x/
  license: GPL v2+
  license_file: COPYING
  summary: gf2x is a library for multiplying polynomials over the binary field.
  description: |
    gf2x is a C/C++ software package containing routines for fast arithmetic
    in GF(2)[x] (multiplication, squaring, GCD) and searching for
    irreducible/primitive trinomials.

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
