travis:
  secure:
    BINSTAR_TOKEN: PI7/wO4rdzLuqe6LogirMZjXXqwihsVsqQm5a4mESfXeK6xYSIqSl3e0Aukn6ghRQWi0F6OmxWzZRF47MIpCPjpC+GgZtj0JxC0w5991RJiCd/r7akvr/O2YL9k+8jqDUvRqsESqw5Tvcz/USf/AFfF2ZfZofUcniNGNxIRVbOc8uzgDoB10MAnQX6vSoKYDbBj8LUajtzDwRHgA2jpI2uVjsdol0/ixabptdXFuspUsSjfFE+kuL6eotx4vlHjZ0aH7CXz+bDFQvybjDSyB+83g73h4nAgDhCUg8dIQciRlgG8HHxlYYuOh21HU4yGdpY9JOFqWw7H1m1SQECYid0+afLx2RCYHU6UMPTW9qS1kGdPtQp2u9QklHI0YJts2JZSLG9xreZfvQZaLdnx6OsAiF3J+yDERgXJAbjqvqIP0Dc4dbebWe18ix7mHz1XWWokfrANaYOJu9jUq4ZnsMFw7XY/piXK9a6NCEkmqrcY5PA9DkcBGAiPQQCGHhkWFwGwqm+8prY/QiwAFrLe9Mjdfl4ZvxttSxrPchHjyCp/YRQWZkdNyfoKs/g2fqvJn4M/JkNIY1OTU7HioBQ3MAJnbatFAzTNdt2wwBAZ9zgcJC+qKV/IRaT+2poza2E9CbZjqAp++IulN27M6o0g0T8nFMUR5mrainsV1ewp0a5k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
